defaults:
  - _self_
  - maniskill3_base
  - maniskill3/obs_mode: state

id: "MS-CartpoleBalance-v1"
max_frames_per_traj: 1000
control_mode: "pd_joint_delta_pos"
camera:
  pose:
    position: [0.0, -2.25, 1.0] # Default [0.0, -4.0, 1.0]
    orientation: [0.7071, 0.0, 0.0, 0.7071] # Default [0.7071, 0.0, 0.0, 0.7071]