defaults:
  - _self_
  - maniskill3_base

id: "UnitreeG1PlaceAppleInBowlTest-v1"
max_frames_per_traj: 100
control_mode: "pd_joint_delta_pos"
log_success: true

default_config:
  camera:
    pose:
      p: null
      q_euler: null
    fov: null
  lighting:
    ambient_light_color: null
    direction:
      light_1: null
      light_2: null
  mo:
    material:
      base_color: null
      texture: null
  ro:
    material:
      base_color: null
      texture: null
  table:
    material:
      base_color: null
      texture: null
  ground:
    material:
      base_color: null
      texture: null
# ===================================================
easy:
  camera_pose_test:
    camera:
      pose:
        p: [0.05, 0, 0.46]
        q_euler: [0, 0.62831853071, 0]
  camera_fov_test:
    camera:
      fov: 1.79519580205
  lighting_direction_test:
    lighting:
      direction:
        light_1: [0.0, 1.0, -1.0]
        light_2: [0.0, 0.0, -1.0]
  lighting_color_test:
    lighting:
      ambient_light_color: [0.8, 0.8, 0.8]
  mo_color_test:
    mo:
      material:
        base_color: [1, 0, 0, 1]
  ro_color_test:
    ro:
      material:
        base_color: [0.643137255, 0.643137255, 0.643137255, 1]
  table_color_test:
    table:
      material:
        base_color: [0, 0, 0, 1]
  ground_color_test:
    ground:
      material:
        base_color: [0.098039216, 0.098039216, 0.098039216, 1]
  mo_texture_test:
    mo:
      material:
        texture: "assets/apple/apple_red_orange_small_dots.png"
  ro_texture_test:
    ro:
      material:
        texture: "assets/bowl/bowl_beige.png"
  table_texture_test:
    table:
      material:
        texture: "assets/table/table_black_ceramic.png"
  ground_texture_test:
    ground:
      material:
        texture: "assets/ground/ground_gray.png"
# ===================================================
medium:
  camera_pose_test:
    camera:
      pose:
        p: [0.05, 0, 0.46]
        q_euler: [0.25, 0.78539816339, 0.25]
  camera_fov_test:
    camera:
      fov: 2.09439510239
  lighting_direction_test:
    lighting:
      direction:
        light_1: [0, 0, -0.1]
        light_2: [1, 1, -0.1]
  lighting_color_test:
    lighting:
      ambient_light_color: [0.0, 0.8, 0.0]
  mo_color_test:
    mo:
      material:
        base_color: [0, 1, 0, 1]
  ro_color_test:
    ro:
      material:
        base_color: [0, 0, 0, 1]
  table_color_test:
    table:
      material:
        base_color: [0, 1, 0, 1]
  ground_color_test:
    ground:
      material:
        base_color: [0, 1, 0, 1]
  mo_texture_test:
    mo:
      material:
        texture: "assets/apple/apple_green.png"
  ro_texture_test:
    ro:
      material:
        texture: "assets/bowl/bowl_blue.png"
  table_texture_test:
    table:
      material:
        texture: "assets/table/table_wood_orange.png"
  ground_texture_test:
    ground:
      material:
        texture: "assets/ground/ground_flower.png"
# ===================================================
hard:
  camera_pose_test:
    camera:
      pose:
        p: [0.1, -0.2, 0.6]
        q_euler: [1, 0.78539816339, 1]
  camera_fov_test:
    camera:
      fov: 2.51327412287
  lighting_direction_test:
    lighting:
      direction:
        light_1: [0, 0, 1]
        light_2: [1, 1, 1]
  lighting_color_test:
    lighting:
      ambient_light_color: [1.0, 0.0, 0.0]
  mo_color_test:
    mo:
      material:
        base_color: [0, 0, 1, 1]
  ro_color_test:
    ro:
      material:
        base_color: [1, 0, 0, 1]
  table_color_test:
    table:
      material:
        base_color: [1, 0, 0, 1]
  ground_color_test:
    ground:
      material:
        base_color: [1, 0, 0, 1]
  mo_texture_test:
    mo:
      material:
        texture: "assets/apple/apple_rotten.png"
  ro_texture_test:
    ro:
      material:
        texture: "assets/bowl/bowl_rainbow_colors_with_apples.png"
  table_texture_test:
    table:
      material:
        texture: "assets/table/table_dense_apples.png"
  ground_texture_test:
    ground:
      material:
        texture: "assets/ground/ground_trees_apples.png"
